import pytest
import pytest_asyncio
import yaml
from fastapi import HTTPException
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker

from app.database import Base
from app.models.dns import DnsConfig
from app.models.node_group import NodeGroup
from app.models.subscription import Subscription
from app.schemas.node_group import NodeGroupCreate
from app.schemas.rule import RuleCreate
from app.schemas.subscription import SubscriptionCreate
from app.services.generate_service import generate_script, generate_yaml
from app.services.node_group_service import create_node_group, preview_node_groups
from app.services.rule_service import create_rule
from app.services.subscription_service import create_subscription, fetch_subscription_nodes


@pytest_asyncio.fixture
async def db_session():
    engine = create_async_engine("sqlite+aiosqlite:///:memory:", future=True)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    SessionLocal = async_sessionmaker(engine, expire_on_commit=False)
    async with SessionLocal() as session:
        yield session

    await engine.dispose()


@pytest.mark.asyncio
async def test_generate_yaml_and_script_respect_switches(db_session):
    sub = Subscription(
        name="primary",
        url="https://example.com/sub",
        is_primary=True,
        raw_nodes=[
            {"name": "HK-1", "type": "ss", "server": "1.1.1.1", "port": 443},
            {"name": "US-1", "type": "ss", "server": "2.2.2.2", "port": 443},
        ],
        fetch_comments=["# generated by test"],
    )
    group = NodeGroup(
        name="Proxy",
        group_type="select",
        regex_rules=["HK"],
        include_entries=[{"type": "node", "value": "DIRECT"}],
    )
    db_session.add_all([sub, group])
    await db_session.commit()
    await create_rule(
        db_session,
        RuleCreate(
            name="rules-1",
            category="default",
            type="domain-suffix",
            value="example.com",
            proxy="Proxy",
            options=[],
        ),
    )

    yaml_result = await generate_yaml(db_session, {"enabled": True, "dns": False})
    assert "# generated by test" in yaml_result["yaml"]
    assert "HK-1" in yaml_result["yaml"]
    assert "DOMAIN-SUFFIX,example.com,Proxy" in yaml_result["yaml"]

    script_result = await generate_script(
        db_session,
        {"enabled": True, "node_groups": True, "rules": True, "dns": False, "exclude_node_proxies": True},
    )
    assert "const modules =" in script_result["script"]
    assert '"name": "Proxy"' in script_result["script"]
    assert '"proxies": [' in script_result["script"]
    assert '"HK-1"' not in script_result["script"]


@pytest.mark.asyncio
async def test_node_group_preview_keeps_regex_dynamic_and_group_entries(db_session):
    sub = Subscription(
        name="sub1",
        url="https://example.com/sub1",
        raw_nodes=[
            {"name": "HK-Node", "type": "ss", "server": "1.1.1.1", "port": 443},
            {"name": "US-Node", "type": "ss", "server": "2.2.2.2", "port": 443},
        ],
    )
    db_session.add(sub)
    await db_session.commit()

    base_group = await create_node_group(
        db_session,
        NodeGroupCreate(
            name="Base",
            include_entries=[{"type": "node", "value": "DIRECT"}],
        ),
    )
    await create_node_group(
        db_session,
        NodeGroupCreate(
            name="Mixed",
            regex_rules=["HK"],
            include_entries=[{"type": "group", "value": base_group.id}],
        ),
    )

    preview = await preview_node_groups(db_session)
    mixed = next(item for item in preview if item["name"] == "Mixed")
    assert "HK-Node" in mixed["resolved_nodes"]
    assert "Base" in mixed["resolved_nodes"]
    assert mixed["include_group_names"] == ["Base"]


@pytest.mark.asyncio
async def test_url_test_group_contains_only_regex_matched_nodes(db_session):
    sub = Subscription(
        name="sub1",
        url="https://example.com/sub1",
        raw_nodes=[
            {"name": "香港 A", "type": "ss", "server": "1.1.1.1", "port": 443},
            {"name": "香港 B", "type": "ss", "server": "2.2.2.2", "port": 443},
            {"name": "美国 C", "type": "ss", "server": "3.3.3.3", "port": 443},
        ],
    )
    group = NodeGroup(
        name="香港",
        group_type="url-test",
        regex_rules=["香港"],
        include_entries=[],
        add_fallback=False,
    )
    db_session.add_all([sub, group])
    await db_session.commit()

    preview = await preview_node_groups(db_session)
    assert next(item for item in preview if item["name"] == "香港")["resolved_nodes"] == [
        "香港 A",
        "香港 B",
    ]

    yaml_result = await generate_yaml(db_session, {"enabled": True, "rules": False, "dns": False})
    config = yaml.safe_load(yaml_result["yaml"])
    assert config["proxy-groups"][0]["proxies"] == ["香港 A", "香港 B"]


@pytest.mark.asyncio
async def test_fetch_subscription_nodes_supports_redirects_and_filters(monkeypatch, db_session):
    class MockResponse:
        def __init__(self, text: str):
            self.text = text
            self.is_redirect = False
            self.status_code = 200
            self.headers = {}
            self.url = "https://example.com"
            self.encoding = "utf-8"

        def raise_for_status(self):
            return None

        async def aiter_bytes(self):
            if hasattr(self, 'text'):
                yield self.text.encode()
            else:
                yield b

    class MockClient:
        def __init__(self, *args, **kwargs):
            assert "follow_redirects" not in kwargs
            assert kwargs.get("trust_env") is False

        async def __aenter__(self):
            return self

        async def __aexit__(self, exc_type, exc, tb):
            return False

        def stream(self, method, url, **kwargs):
            import contextlib
            @contextlib.asynccontextmanager
            async def _ctx():
                resp = await self.get(url)
                yield resp
            return _ctx()

        async def get(self, url):
            assert url == "https://example.com/sub"
            return MockResponse(
                "proxies:\n"
                "  - name: HK-1\n"
                "    type: ss\n"
                "    server: 1.1.1.1\n"
                "    port: 443\n"
                "  - name: US-1\n"
                "    type: ss\n"
                "    server: 2.2.2.2\n"
                "    port: 443\n"
            )

    monkeypatch.setattr("app.services.subscription_service.httpx.AsyncClient", MockClient)

    item = Subscription(
        name="sub",
        url="https://example.com/sub",
        is_primary=False,
        node_prefix="TEST",
        filter_regex=["HK"],
    )
    db_session.add(item)
    await db_session.commit()
    await db_session.refresh(item)

    updated = await fetch_subscription_nodes(db_session, item)
    assert [node["name"] for node in updated.raw_nodes] == ["TEST-HK-1"]
    assert [node["name"] for node in updated.source_nodes] == ["HK-1", "US-1"]
    assert updated.fetch_comments == []


@pytest.mark.asyncio
async def test_fetch_subscription_empty_regex_selects_all_then_manual_excludes(monkeypatch, db_session):
    class MockResponse:
        is_redirect = False
        status_code = 200
        headers = {}
        url = "https://example.com"
        encoding = "utf-8"
        text = (
            "proxies:\n"
            "  - name: HK-1\n"
            "    type: ss\n"
            "    server: 1.1.1.1\n"
            "    port: 443\n"
            "  - name: US-1\n"
            "    type: ss\n"
            "    server: 2.2.2.2\n"
            "    port: 443\n"
            "  - name: JP-1\n"
            "    type: ss\n"
            "    server: 3.3.3.3\n"
            "    port: 443\n"
        )

        def raise_for_status(self):
            return None

        async def aiter_bytes(self):
            if hasattr(self, 'text'):
                yield self.text.encode()
            else:
                yield b

    class MockClient:
        def __init__(self, *args, **kwargs):
            self.is_redirect = False
            self.status_code = 200
            self.headers = {}
            self.url = "https://example.com"
            pass

        async def __aenter__(self):
            return self

        async def __aexit__(self, exc_type, exc, tb):
            return False

        def stream(self, method, url, **kwargs):
            import contextlib
            @contextlib.asynccontextmanager
            async def _ctx():
                resp = await self.get(url)
                yield resp
            return _ctx()

        async def get(self, url):
            return MockResponse()

    monkeypatch.setattr("app.services.subscription_service.httpx.AsyncClient", MockClient)

    item = Subscription(
        name="sub-select",
        url="https://example.com/sub",
        is_primary=False,
        filter_regex=[],
        include_node_names=["US-1"],
        exclude_node_names=["JP-1"],
    )
    db_session.add(item)
    await db_session.commit()
    await db_session.refresh(item)

    updated = await fetch_subscription_nodes(db_session, item)
    assert [node["name"] for node in updated.source_nodes] == ["HK-1", "US-1", "JP-1"]
    assert [node["name"] for node in updated.raw_nodes] == ["sub-select-HK-1", "sub-select-US-1"]


@pytest.mark.asyncio
async def test_create_rule_rejects_missing_proxy_target(db_session):
    with pytest.raises(HTTPException) as exc_info:
        await create_rule(
            db_session,
            RuleCreate(
                name="bad-rule",
                category="default",
                sort_order=0,
                enabled=True,
                type="match",
                value="",
                proxy="MissingGroup",
                options=[],
            ),
        )

    assert exc_info.value.status_code == 400
    assert "MissingGroup" in str(exc_info.value.detail)


@pytest.mark.asyncio
async def test_create_rule_keeps_named_items(db_session):
    group = NodeGroup(
        name="Proxy",
        group_type="select",
        include_entries=[{"type": "node", "value": "DIRECT"}],
    )
    db_session.add(group)
    await db_session.commit()

    item = await create_rule(
        db_session,
        RuleCreate(
            name="Google 走 Proxy",
            category="default",
            type="domain-suffix",
            value="google.com",
            proxy="Proxy",
            options=[],
        ),
    )

    assert item.name == "Google 走 Proxy"
    assert item.type == "DOMAIN-SUFFIX"


@pytest.mark.asyncio
async def test_dns_raw_full_dns_document_is_unwrapped(db_session):
    db_session.add(
        DnsConfig(
            id=1,
            enabled=True,
            raw_yaml="dns:\n  enable: true\n  enhanced-mode: fake-ip\n",
        )
    )
    await db_session.commit()

    yaml_result = await generate_yaml(db_session, {"enabled": True, "dns": True})
    assert "dns:\n  enable: true" in yaml_result["yaml"]
    assert "dns:\n  dns:" not in yaml_result["yaml"]

    script_result = await generate_script(db_session, {"enabled": True, "dns": True})
    assert '"enable": true' in script_result["script"]


@pytest.mark.asyncio
async def test_create_subscription_rejects_invalid_filter_regex(db_session):
    with pytest.raises(HTTPException) as exc_info:
        await create_subscription(
            db_session,
            SubscriptionCreate(
                name="bad-regex",
                url="https://example.com/sub",
                filter_regex=["HK", "["],
            ),
        )

    assert exc_info.value.status_code == 400
    assert "Invalid filter_regex #2" in str(exc_info.value.detail)


@pytest.mark.asyncio
async def test_fetch_failure_records_error(monkeypatch, db_session):
    class MockClient:
        def __init__(self, *args, **kwargs):
            assert "follow_redirects" not in kwargs
            assert kwargs.get("trust_env") is False

        async def __aenter__(self):
            return self

        async def __aexit__(self, exc_type, exc, tb):
            return False

        def stream(self, method, url, **kwargs):
            import contextlib
            @contextlib.asynccontextmanager
            async def _ctx():
                resp = await self.get(url)
                yield resp
            return _ctx()

        async def get(self, url):
            raise RuntimeError("network down")

    monkeypatch.setattr("app.services.subscription_service.httpx.AsyncClient", MockClient)

    item = Subscription(name="sub-error", url="https://example.com/sub")
    db_session.add(item)
    await db_session.commit()
    await db_session.refresh(item)

    with pytest.raises(RuntimeError):
        await fetch_subscription_nodes(db_session, item)

    assert item.last_fetch_error == "network down"
    assert item.fetch_failed_count == 1


@pytest.mark.asyncio
async def test_generate_rules_emits_match_without_empty_value(db_session):
    await create_rule(
        db_session,
        RuleCreate(
            name="match-rule",
            category="default",
            type="match",
            value="ignored",
            proxy="DIRECT",
            options=[],
        ),
    )

    yaml_result = await generate_yaml(db_session, {"enabled": True, "rules": True})
    assert "MATCH,DIRECT" in yaml_result["yaml"]
    assert "MATCH,,DIRECT" not in yaml_result["yaml"]


@pytest.mark.asyncio
async def test_create_manual_node_subscription_parses_links_without_storing_raw_link(db_session):
    from app.schemas.subscription import ManualNodeCreate
    from app.services.subscription_service import create_manual_node_subscription

    link = (
        "vless://00000000-0000-4000-8000-000000000002@example.net:8443"
        "?type=tcp&security=reality&pbk=key&fp=chrome&sni=www.example.net"
        "&sid=beef&flow=xtls-rprx-vision#Manual%20Node"
    )

    item = await create_manual_node_subscription(
        db_session,
        ManualNodeCreate(name="manual", node_links=link, node_prefix="MN"),
    )

    assert item.url == "manual://nodes"
    assert link not in item.url
    assert [node["name"] for node in item.manual_nodes] == ["Manual Node"]
    assert [node["name"] for node in item.raw_nodes] == ["MN-Manual Node"]
    assert item.raw_nodes[0]["reality-opts"]["public-key"] == "key"


@pytest.mark.asyncio
async def test_subscription_manual_nodes_are_merged_with_fetched_nodes(monkeypatch, db_session):
    class MockResponse:
        is_redirect = False
        status_code = 200
        headers = {}
        url = "https://example.com"
        encoding = "utf-8"
        text = (
            "proxies:\n"
            "  - name: HK-1\n"
            "    type: ss\n"
            "    server: 1.1.1.1\n"
            "    port: 443\n"
        )

        def raise_for_status(self):
            return None

        async def aiter_bytes(self):
            if hasattr(self, 'text'):
                yield self.text.encode()
            else:
                yield b

    class MockClient:
        def __init__(self, *args, **kwargs):
            self.is_redirect = False
            self.status_code = 200
            self.headers = {}
            self.url = "https://example.com"
            pass

        async def __aenter__(self):
            return self

        async def __aexit__(self, exc_type, exc, tb):
            return False

        def stream(self, method, url, **kwargs):
            import contextlib
            @contextlib.asynccontextmanager
            async def _ctx():
                resp = await self.get(url)
                yield resp
            return _ctx()

        async def get(self, url):
            return MockResponse()

    monkeypatch.setattr("app.services.subscription_service.httpx.AsyncClient", MockClient)

    item = Subscription(
        name="sub-manual",
        url="https://example.com/sub",
        node_prefix="SUB",
        manual_nodes=[{"name": "Manual-1", "type": "vless", "server": "manual.example", "port": 443}],
    )
    db_session.add(item)
    await db_session.commit()
    await db_session.refresh(item)

    updated = await fetch_subscription_nodes(db_session, item)
    assert [node["name"] for node in updated.source_nodes] == ["HK-1"]
    assert [node["name"] for node in updated.manual_nodes] == ["Manual-1"]
    assert [node["name"] for node in updated.raw_nodes] == ["SUB-HK-1", "SUB-Manual-1"]


@pytest.mark.asyncio
async def test_create_subscription_accepts_manual_node_links(db_session):
    link = (
        "vless://00000000-0000-4000-8000-000000000005@example.test:443"
        "?type=tcp&security=reality&pbk=key&fp=chrome&sni=www.example.test"
        "&sid=abcd&flow=xtls-rprx-vision#Inline%20Manual"
    )

    item = await create_subscription(
        db_session,
        SubscriptionCreate(
            name="sub-with-inline-manual",
            url="https://example.com/sub",
            node_prefix="SM",
            manual_node_links=link,
        ),
    )

    assert [node["name"] for node in item.manual_nodes] == ["Inline Manual"]
    assert [node["name"] for node in item.raw_nodes] == ["SM-Inline Manual"]


@pytest.mark.asyncio
async def test_fetch_subscription_nodes_uses_runtime_proxy_setting(monkeypatch, db_session):
    from app.models.security_settings import SecuritySettings

    class MockResponse:
        is_redirect = False
        status_code = 200
        headers = {}
        url = "https://example.com"
        encoding = "utf-8"
        text = (
            "proxies:\n"
            "  - name: HK-1\n"
            "    type: ss\n"
            "    server: 1.1.1.1\n"
            "    port: 443\n"
        )
        headers = {}
        encoding = "utf-8"

        def raise_for_status(self):
            return None

        async def aiter_bytes(self):
            if hasattr(self, 'text'):
                yield self.text.encode()
            else:
                yield b

    class MockClient:
        def __init__(self, *args, **kwargs):
            self.is_redirect = False
            self.status_code = 200
            self.headers = {}
            self.url = "https://example.com"
            assert kwargs.get("proxy") == "http://127.0.0.1:7890"
            assert kwargs.get("trust_env") is False

        async def __aenter__(self):
            return self

        async def __aexit__(self, exc_type, exc, tb):
            return False

        def stream(self, method, url, **kwargs):
            import contextlib
            @contextlib.asynccontextmanager
            async def _ctx():
                resp = await self.get(url)
                yield resp
            return _ctx()

        async def get(self, url):
            return MockResponse()

    monkeypatch.setattr("app.services.subscription_service.httpx.AsyncClient", MockClient)

    db_session.add(SecuritySettings(id=1, fetch_proxy_enabled=True, fetch_proxy_url="http://127.0.0.1:7890"))
    item = Subscription(name="sub-proxy", url="https://example.com/sub")
    db_session.add(item)
    await db_session.commit()
    await db_session.refresh(item)

    updated = await fetch_subscription_nodes(db_session, item)
    assert [node["name"] for node in updated.source_nodes] == ["HK-1"]
