"""initial schema

Revision ID: d49593de8ad6
Revises: 
Create Date: 2026-06-27 16:33:10.044826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49593de8ad6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('snapshot_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_snapshots_id'), 'config_snapshots', ['id'], unique=False)
    op.create_table('dns_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_yaml', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generate_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('subscriptions', sa.Boolean(), nullable=False),
    sa.Column('node_groups', sa.Boolean(), nullable=False),
    sa.Column('rules', sa.Boolean(), nullable=False),
    sa.Column('dns', sa.Boolean(), nullable=False),
    sa.Column('exclude_node_proxies', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('group_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('regex_rules', sa.JSON(), nullable=False),
    sa.Column('include_nodes', sa.JSON(), nullable=False),
    sa.Column('include_group_ids', sa.JSON(), nullable=False),
    sa.Column('include_group_nodes_ids', sa.JSON(), nullable=False),
    sa.Column('include_entries', sa.JSON(), nullable=False),
    sa.Column('add_fallback', sa.Boolean(), nullable=False),
    sa.Column('exclude_nodes', sa.JSON(), nullable=False),
    sa.Column('url_test_config', sa.JSON(), nullable=False),
    sa.Column('load_balance_config', sa.JSON(), nullable=False),
    sa.Column('fallback_config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_node_groups_id'), 'node_groups', ['id'], unique=False)
    op.create_table('rule_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rule_categories_id'), 'rule_categories', ['id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('proxy', sa.String(length=160), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_category'), 'rules', ['category'], unique=False)
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_table('security_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_enabled', sa.Boolean(), nullable=False),
    sa.Column('protect_frontend', sa.Boolean(), nullable=False),
    sa.Column('protect_api', sa.Boolean(), nullable=False),
    sa.Column('protect_exports', sa.Boolean(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('fetch_proxy_enabled', sa.Boolean(), nullable=False),
    sa.Column('fetch_proxy_url', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('update_interval', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('node_prefix', sa.String(length=120), nullable=True),
    sa.Column('filter_regex', sa.JSON(), nullable=False),
    sa.Column('include_node_names', sa.JSON(), nullable=False),
    sa.Column('exclude_node_names', sa.JSON(), nullable=False),
    sa.Column('source_nodes', sa.JSON(), nullable=False),
    sa.Column('manual_nodes', sa.JSON(), nullable=False),
    sa.Column('raw_nodes', sa.JSON(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetch_error', sa.Text(), nullable=True),
    sa.Column('fetch_failed_count', sa.Integer(), nullable=False),
    sa.Column('fetch_comments', sa.JSON(), nullable=False),
    sa.Column('subscription_userinfo', sa.Text(), nullable=True),
    sa.Column('profile_update_interval', sa.String(length=40), nullable=True),
    sa.Column('profile_web_page_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_primary'), 'subscriptions', ['is_primary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_is_primary'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('security_settings')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_category'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_rule_categories_id'), table_name='rule_categories')
    op.drop_table('rule_categories')
    op.drop_index(op.f('ix_node_groups_id'), table_name='node_groups')
    op.drop_table('node_groups')
    op.drop_table('generate_config')
    op.drop_table('dns_config')
    op.drop_index(op.f('ix_config_snapshots_id'), table_name='config_snapshots')
    op.drop_table('config_snapshots')
    # ### end Alembic commands ###
